# Generated by Django 3.2.16 on 2022-11-05 22:34

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'White'), ('#000000', 'Black'), ('#8B21DF', 'Purple'), ('#FBA76F', 'Orange'), ('#CA3333', 'Red'), ('#1300EA', 'Blue')])),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('manual', 'Created manually'), ('generated', 'Generated')], default='manual', max_length=50)),
                ('generate_rules', models.JSONField(blank=True, null=True)),
                ('create_rules', models.JSONField(blank=True, null=True)),
                ('markup', models.FileField(blank=True, null=True, upload_to='markup')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'White'), ('#000000', 'Black'), ('#8B21DF', 'Purple'), ('#FBA76F', 'Orange'), ('#CA3333', 'Red'), ('#1300EA', 'Blue')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_snapshot_collections', to=settings.AUTH_USER_MODEL)),
                ('type_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_snapshot_collections', to='snapshot.typecollection')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='snapshot_file')),
                ('is_marked', models.BooleanField(default=False)),
                ('snapshot_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='snapshot.snapshotcollection')),
            ],
        ),
    ]
