# Generated by Django 3.2.16 on 2022-11-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='snapshot_preview'),
        ),
    ]
