# Generated by Django 3.2.16 on 2022-11-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0002_snapshot_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='snapshot_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_snapshots', to='snapshot.snapshotcollection'),
        ),
    ]
