# Generated by Django 3.2.16 on 2022-11-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0004_alter_snapshot_snapshot_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshotcollection',
            name='type_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_collections', to='snapshot.typecollection'),
        ),
    ]
