# Generated by Django 3.2.16 on 2022-11-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0005_alter_snapshotcollection_type_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotcollection',
            name='archive',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snapshotcollection',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='typecollection',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
